[package]
name = "structs"
version = "0.1.0"
authors = ["Michelle Tham <mtham101@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
